# Generated by Django 3.0.7 on 2020-06-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200606_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
